version: '3.7'

services:
  scrapper-app:
    image: node:alpine
    env_file:
      - ./.env
    volumes:
      - ./src:/opt/streamtv/src:delegated
      - ./test:/opt/streamtv/test:delegated
      - ./package.json:/opt/streamtv/package.json
      - ./package-lock.json:/opt/streamtv/package-lock.json
      - ./tsconfig.json:/opt/streamtv/tsconfig.json
      - ./var:/opt/streamtv/var:delegated
      - ./docker/node_modules:/opt/streamtv/node_modules:delegated
    working_dir: /opt/streamtv
    entrypoint: |
      /bin/sh -c 'npm install; npm run build'