apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamtv-cache
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/streamtv-cache/
  storageClassName: standard