apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamtv-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: /data/streamtv-data/
  storageClassName: standard