apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamtv-data
  namespace: streamtv
spec:
  storageClassName: standard
  volumeName: streamtv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi