apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamtv-cache
  namespace: streamtv
spec:
  storageClassName: standard
  volumeName: streamtv-cache
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi